name: Reusable build microservices

on:
  workflow_call:
    inputs:
      version:
        description: "Version of gainsight-sync-ms to be built."
        required: false
        type: string
  push:
    branches:
      - release

env:
  NODE_VERSION: ${{ '24' }}

jobs:
  build-microservices:
    name: Build microservices
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Resolve build version
        run: echo "BUILD_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Align version in cumulocity.json
        run: |
          cat cumulocity.json | jq --arg version "${{ env.BUILD_VERSION }}" '.version = $version' > .tmp.json && mv .tmp.json cumulocity.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --squash --progress=plain \
            --tag gainsight-sync-ms:${{ env.BUILD_VERSION }} \
            --tag gainsight-sync-ms:latest \
            --target=production \
            -f ./Dockerfile .
          mkdir -p .tmp
          docker save gainsight-sync-ms:${{ env.BUILD_VERSION }} > image.tar
          zip .tmp/gainsight-sync-ms-${{ env.BUILD_VERSION }}.zip cumulocity.json image.tar
          rm image.tar

      - name: Upload microservice artifact
        uses: actions/upload-artifact@v6
        with:
          name: gainsight-sync-ms-${{ env.BUILD_VERSION }}
          if-no-files-found: error
          retention-days: 5
          path: .tmp/gainsight-sync-ms-${{ env.BUILD_VERSION }}.zip

